#!/usr/bin/env python3
"""Dataset QA for twin episodes (report-only; no auto-delete unless exact dupes)."""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
from collections import defaultdict
from difflib import SequenceMatcher
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from scripts._common import EPISODES_DIR, load_episodes  # noqa: E402


def _norm(text: str) -> str:
    return re.sub(r"\s+", " ", text.lower()).strip()


def _doc_blob(ep: dict) -> str:
    parts = []
    for doc in ep.get("retrieved_docs") or []:
        if isinstance(doc, dict):
            parts.append(str(doc.get("text") or ""))
    return "\n".join(parts)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--episodes-dir", type=Path, default=EPISODES_DIR)
    parser.add_argument(
        "--write-report",
        type=Path,
        default=ROOT / "QA_REPORT.md",
        help="Markdown report path (default: QA_REPORT.md)",
    )
    parser.add_argument("--similarity", type=float, default=0.92)
    args = parser.parse_args()

    directory = args.episodes_dir if args.episodes_dir.is_absolute() else ROOT / args.episodes_dir
    episodes = [ep for ep in load_episodes([directory]) if ep.get("id")]
    by_id = {str(ep["id"]): ep for ep in episodes}

    findings: dict = {
        "n_episodes": len(episodes),
        "twin_query_mismatch": [],
        "attack_missing_injection": [],
        "benign_has_injection": [],
        "exact_content_dupes": [],
        "near_duplicates": [],
        "notes": [],
    }

    # Twin pairs atk_XXX / ben_XXX
    for eid, ep in sorted(by_id.items()):
        if not eid.startswith("atk_"):
            continue
        twin_id = "ben_" + eid[4:]
        twin = by_id.get(twin_id)
        if twin is None:
            findings["notes"].append(f"no twin file for {eid}")
            continue
        if ep.get("user_query") != twin.get("user_query"):
            findings["twin_query_mismatch"].append({"attack": eid, "benign": twin_id})

    for eid, ep in sorted(by_id.items()):
        inj = ep.get("injection") or {}
        present = bool(inj.get("present"))
        if ep.get("split") == "attack" and not present:
            findings["attack_missing_injection"].append(eid)
        if ep.get("split") == "benign" and present:
            findings["benign_has_injection"].append(eid)

    # Exact duplicates of (user_query + docs)
    buckets: dict[str, list[str]] = defaultdict(list)
    for eid, ep in by_id.items():
        blob = _norm(str(ep.get("user_query") or "") + "\n" + _doc_blob(ep))
        digest = hashlib.sha256(blob.encode("utf-8")).hexdigest()
        buckets[digest].append(eid)
    for ids in buckets.values():
        if len(ids) > 1:
            findings["exact_content_dupes"].append(sorted(ids))

    # Near-duplicate pairs (high similarity)
    items = sorted(by_id.items())
    for i, (id_a, ep_a) in enumerate(items):
        blob_a = _norm(str(ep_a.get("user_query") or "") + "\n" + _doc_blob(ep_a))
        for id_b, ep_b in items[i + 1 :]:
            # skip exact attack/benign twin same query with different docs intentionally
            if {id_a[:3], id_b[:3]} == {"atk", "ben"} and id_a[4:] == id_b[4:]:
                continue
            blob_b = _norm(str(ep_b.get("user_query") or "") + "\n" + _doc_blob(ep_b))
            ratio = SequenceMatcher(None, blob_a, blob_b).ratio()
            if ratio >= args.similarity:
                findings["near_duplicates"].append(
                    {"a": id_a, "b": id_b, "similarity": round(ratio, 4)}
                )

    # Markdown report
    report_path = args.write_report if args.write_report.is_absolute() else ROOT / args.write_report
    lines = [
        "# Dataset QA report",
        "",
        "Generated by `scripts/qa_episodes.py`. Report-only; no episodes auto-deleted.",
        "",
        f"- Episodes scanned: **{findings['n_episodes']}**",
        f"- Twin query mismatches: **{len(findings['twin_query_mismatch'])}**",
        f"- Attack missing injection: **{len(findings['attack_missing_injection'])}**",
        f"- Benign with injection: **{len(findings['benign_has_injection'])}**",
        f"- Exact content duplicate groups: **{len(findings['exact_content_dupes'])}**",
        f"- Near-duplicate pairs (similarity ≥ {args.similarity}): **{len(findings['near_duplicates'])}**",
        "",
        "## Findings",
        "",
    ]
    if not any(
        findings[k]
        for k in (
            "twin_query_mismatch",
            "attack_missing_injection",
            "benign_has_injection",
            "exact_content_dupes",
            "near_duplicates",
        )
    ):
        lines.append("No structural issues found in the twin seed set under the checks above.")
        lines.append("")
    else:
        lines.append("```json")
        lines.append(json.dumps({k: findings[k] for k in findings if k != "n_episodes"}, indent=2))
        lines.append("```")
        lines.append("")
    lines.append("## Notes")
    lines.append("")
    lines.append("- Twin attack/benign pairs intentionally share `user_query` but differ in docs.")
    lines.append("- Near-duplicate detection is lexical; high similarity is a signal, not auto-removal.")
    lines.append("- This report does not include ASR/utility numbers.")
    lines.append("")
    report_path.write_text("\n".join(lines), encoding="utf-8")

    print(json.dumps(findings, indent=2))
    print(f"wrote {report_path}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
