"""Harness version and execution mode constants (P4.2.4+)."""

HARNESS_VERSION = "p4.3-eval-harness-v1"

# How optional surfaces are applied (recorded in traces / evaluation results).
EXECUTION_MODE_LIVE = "LIVE"
EXECUTION_MODE_STATIC_REPLAY = "STATIC_REPLAY"
EXECUTION_MODE_STATIC_ADAPTIVE_REPLAY = "STATIC_ADAPTIVE_REPLAY"
EXECUTION_MODE_LIVE_ADAPTIVE = "LIVE_ADAPTIVE"
EXECUTION_MODE_EXPLICIT_UNSUPPORTED = "EXPLICIT_UNSUPPORTED"
EXECUTION_MODE_INTER_AGENT_REPLAY = "INTER_AGENT_REPLAY"
EXECUTION_MODE_MULTI_AGENT_EXECUTION = "MULTI_AGENT_EXECUTION"

MULTI_AGENT_CAPABILITY = "MULTI_AGENT_EXECUTION_SUPPORTED"
ADAPTIVE_CAPABILITY_STATIC_ONLY = "STATIC_ADAPTIVE_REPLAY"
ADAPTIVE_CAPABILITY_LIVE = "LIVE_ADAPTIVE"
